import MealPlan from '../models/MealPlan.js';
import { generateMealPlanWithAI, regenerateSingleMealWithAI } from '../services/aiService.js';
import { listMealOptions } from '../services/indianMealTemplates.js';
import { findCheatDayConfig, getCheatMessage } from '../utils/cheatDayMessages.js';
import { recommendMeals } from '../services/mlClient.js';

const MEAL_COURSE_MAP = { breakfast: 'snack', lunch: 'main course', dinner: 'main course', snack: 'snack' };
const MEAL_SERVING_GRAMS = { breakfast: 200, lunch: 280, dinner: 280, snack: 120 };

// Converts a real indian_food.csv + ifct2017-nutrition dish (from the ML
// recommender, per-100g macros) into the same shape listMealOptions() already
// returns, so MealCard.jsx needs no changes to render either source.
function mlDishToMealOption(dish, mealType) {
  const grams = MEAL_SERVING_GRAMS[mealType] || 250;
  const scale = grams / 100;
  const region = String(dish.region || 'any').toLowerCase();
  const cuisine = ['north', 'south', 'east', 'west'].includes(region) ? region
    : region.startsWith('north') ? 'north' : region.startsWith('south') ? 'south' : 'any';

  return {
    type: mealType,
    name: dish.name,
    prepTime: (dish.prep_time || 0) + (dish.cook_time || 0) || 20,
    cuisine,
    nutritionSource: dish.nutrition_source,
    foods: [{
      name: dish.name,
      quantity: `${grams}g`,
      calories: Math.round((dish.calories_per_100g || 0) * scale),
      protein: Math.round((dish.protein_g || 0) * scale),
      carbs: Math.round((dish.carbs_g || 0) * scale),
      fat: Math.round((dish.fat_g || 0) * scale),
      fiber: Math.round((dish.fiber_g || 0) * scale)
    }]
  };
}

function recalcTotals(meals) {
  return meals.reduce((acc, m) => ({
    calories: acc.calories + (m.totalCalories || 0),
    protein: acc.protein + (m.foods || []).reduce((s, f) => s + (f.protein || 0), 0),
    carbs: acc.carbs + (m.foods || []).reduce((s, f) => s + (f.carbs || 0), 0),
    fat: acc.fat + (m.foods || []).reduce((s, f) => s + (f.fat || 0), 0),
    fiber: acc.fiber + (m.foods || []).reduce((s, f) => s + (f.fiber || 0), 0)
  }), { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 });
}

function startOfDay(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

function buildNutritionContext(user, overrides = {}) {
  return {
    goal: user.currentGoal,
    dietType: user.preferences?.dietType,
    budget: user.preferences?.budget,
    cookingSkill: user.preferences?.cookingSkill,
    allergies: user.healthProfile?.allergies || [],
    chronicConditions: user.healthProfile?.chronicConditions || [],
    cuisine: user.preferences?.cuisine,
    cuisinePerMeal: user.preferences?.cuisinePerMeal,
    ...overrides
  };
}

export async function generateMealPlan(req, res) {
  try {
    const date = req.body?.date ? startOfDay(req.body.date) : startOfDay(new Date());
    const existing = await MealPlan.findOne({ userId: req.user._id, date });

    const cheatConfig = findCheatDayConfig(req.user, date, 'meal_only');
    if (cheatConfig) {
      const cheatFields = {
        meals: [], dailyTotals: { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0 }, targetCalories: 0,
        isCheatDay: true, cheatMessage: getCheatMessage('meal_only'),
        aiExplanation: 'Configured cheat day — no meal plan generated by design.'
      };
      const mealPlan = existing ? Object.assign(existing, cheatFields) : new MealPlan({ ...cheatFields, userId: req.user._id, date });
      await mealPlan.save();
      return res.json(mealPlan);
    }

    const userContext = buildNutritionContext(req.user, req.body || {});
    const aiPlan = await generateMealPlanWithAI(userContext);

    const mealPlan = existing
      ? Object.assign(existing, { ...aiPlan, isCheatDay: false, cheatMessage: undefined })
      : new MealPlan({ ...aiPlan, userId: req.user._id, date });
    await mealPlan.save();

    res.json(mealPlan);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getTodayMealPlan(req, res) {
  try {
    const mealPlan = await MealPlan.findOne({ userId: req.user._id, date: startOfDay(new Date()) }).sort({ createdAt: -1 });
    if (!mealPlan) {
      return res.status(404).json({ exists: false, message: 'No meal plan generated yet for today.' });
    }
    res.json(mealPlan);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getMealPlanRange(req, res) {
  try {
    const { from, to } = req.query;
    if (!from || !to) {
      return res.status(400).json({ message: 'Query params "from" and "to" (YYYY-MM-DD) are required.' });
    }
    const mealPlans = await MealPlan.find({
      userId: req.user._id,
      date: { $gte: startOfDay(from), $lte: new Date(new Date(to).setHours(23, 59, 59, 999)) }
    }).sort({ date: 1 });
    res.json(mealPlans);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function generateWeekOfMealPlans(req, res) {
  try {
    const weekStartDate = req.body?.weekStartDate ? startOfDay(req.body.weekStartDate) : startOfDay(new Date());
    const userContext = buildNutritionContext(req.user);

    const created = [];
    for (let i = 0; i < 7; i++) {
      const date = new Date(weekStartDate);
      date.setDate(date.getDate() + i);

      const aiPlan = await generateMealPlanWithAI(userContext);
      const existing = await MealPlan.findOne({ userId: req.user._id, date });
      const mealPlan = existing ? Object.assign(existing, aiPlan) : new MealPlan({ ...aiPlan, userId: req.user._id, date });
      await mealPlan.save();
      created.push(mealPlan);
    }

    res.json(created);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function regenerateSingleMeal(req, res) {
  try {
    const { mealPlanId, mealType } = req.params;
    const mealPlan = await MealPlan.findOne({ _id: mealPlanId, userId: req.user._id });
    if (!mealPlan) return res.status(404).json({ message: 'Meal plan not found' });

    // One-off override (e.g. "swap to vegetarian just for this meal") without
    // permanently changing the user's stored diet preference.
    const { dietTypeOverride, cuisineOverride } = req.body || {};
    const userContext = buildNutritionContext(req.user, {
      ...(dietTypeOverride ? { dietType: dietTypeOverride } : {}),
      ...(cuisineOverride ? { cuisine: cuisineOverride } : {})
    });
    const newMeal = await regenerateSingleMealWithAI(mealType, userContext);

    const idx = mealPlan.meals.findIndex(m => m.type === mealType);
    if (idx !== -1) mealPlan.meals[idx] = newMeal;
    else mealPlan.meals.push(newMeal);

    mealPlan.dailyTotals = recalcTotals(mealPlan.meals);

    await mealPlan.save();
    res.json({ mealPlan, updatedMeal: newMeal });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

// Lists real, diet-appropriate dish alternatives for a meal slot so the user can pick
// one themselves instead of only ever getting a single blind AI-picked swap.
export async function getMealAlternatives(req, res) {
  try {
    const { mealType } = req.params;
    const cuisine = req.query.cuisine || req.user.preferences?.cuisinePerMeal?.[mealType] || req.user.preferences?.cuisine;
    const dietType = req.query.dietType || req.user.preferences?.dietType;

    const mlDishes = await recommendMeals({
      diet_type: dietType || 'vegetarian',
      cuisine: (cuisine && cuisine !== 'any') ? cuisine : 'any',
      course: MEAL_COURSE_MAP[mealType] || 'main course',
      goal: 'balanced',
      top_k: 6
    });

    const options = (mlDishes && mlDishes.length > 0)
      ? mlDishes.map(d => mlDishToMealOption(d, mealType))
      : listMealOptions(mealType, dietType, cuisine);

    res.json({ options });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

// Sets a meal directly — either a picked alternative or a fully user-entered custom
// meal — bypassing the AI generator entirely, since not every swap should be an AI call.
export async function setMealManual(req, res) {
  try {
    const { mealPlanId, mealType } = req.params;
    const { option, customMeal } = req.body || {};
    const mealPlan = await MealPlan.findOne({ _id: mealPlanId, userId: req.user._id });
    if (!mealPlan) return res.status(404).json({ message: 'Meal plan not found' });

    const source = customMeal || option;
    if (!source || !source.name || !Array.isArray(source.foods) || source.foods.length === 0) {
      return res.status(400).json({ message: 'A meal name and at least one food item are required.' });
    }

    const totalCalories = source.totalCalories ?? source.foods.reduce((s, f) => s + (Number(f.calories) || 0), 0);
    const newMeal = {
      type: mealType,
      name: source.name,
      prepTime: Number(source.prepTime) || 10,
      totalCalories,
      foods: source.foods.map(f => ({
        name: f.name,
        quantity: f.quantity || '1 serving',
        calories: Number(f.calories) || 0,
        protein: Number(f.protein) || 0,
        carbs: Number(f.carbs) || 0,
        fat: Number(f.fat) || 0,
        fiber: Number(f.fiber) || 0
      })),
      consumed: false,
      consumedAt: null
    };

    const idx = mealPlan.meals.findIndex(m => m.type === mealType);
    if (idx !== -1) mealPlan.meals[idx] = newMeal;
    else mealPlan.meals.push(newMeal);

    mealPlan.dailyTotals = recalcTotals(mealPlan.meals);
    await mealPlan.save();
    res.json({ mealPlan, updatedMeal: newMeal });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

// Marks a meal as actually eaten (or un-eaten) — this is the real signal that drives
// "consumed so far today" progress, distinct from the AI-generated plan's totals
// which represent what was planned, not what was actually eaten.
export async function setMealConsumed(req, res) {
  try {
    const { mealPlanId, mealType } = req.params;
    const { consumed } = req.body;
    const mealPlan = await MealPlan.findOne({ _id: mealPlanId, userId: req.user._id });
    if (!mealPlan) return res.status(404).json({ message: 'Meal plan not found' });

    const meal = mealPlan.meals.find(m => m.type === mealType);
    if (!meal) return res.status(404).json({ message: 'Meal not found in this plan' });

    meal.consumed = !!consumed;
    meal.consumedAt = consumed ? new Date() : null;
    await mealPlan.save();

    res.json(mealPlan);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getGroceryList(req, res) {
  try {
    const { from, to } = req.query;
    const rangeFrom = from ? startOfDay(from) : startOfDay(new Date());
    const rangeTo = to ? new Date(new Date(to).setHours(23, 59, 59, 999)) : new Date(new Date(rangeFrom).setDate(rangeFrom.getDate() + 6));

    const mealPlans = await MealPlan.find({ userId: req.user._id, date: { $gte: rangeFrom, $lte: rangeTo } });

    const itemMap = new Map();
    for (const plan of mealPlans) {
      for (const meal of plan.meals || []) {
        for (const food of meal.foods || []) {
          const key = food.name.toLowerCase().trim();
          if (!itemMap.has(key)) {
            itemMap.set(key, { name: food.name, quantities: [], mealsUsedIn: 0 });
          }
          const entry = itemMap.get(key);
          if (food.quantity) entry.quantities.push(food.quantity);
          entry.mealsUsedIn += 1;
        }
      }
    }

    const items = Array.from(itemMap.values()).map(({ name, quantities, mealsUsedIn }) => ({
      name,
      totalQuantity: quantities.join(' + '),
      mealsUsedIn
    }));

    res.json({ from: rangeFrom, to: rangeTo, items });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}
