import Workout from '../models/Workout.js';
import WorkoutVersion from '../models/WorkoutVersion.js';
import { generateWorkoutWithAI, generateWeeklyWorkoutPlanWithAI } from '../services/aiService.js';
import { buildYogaSession } from '../services/yogaService.js';
import { applyStreakUpdate, pauseStreakForToday, getStreakState } from '../utils/streak.js';
import { recordWorkoutCompletion } from '../utils/gamification.js';
import { findCheatDayConfig, getCheatMessage } from '../utils/cheatDayMessages.js';

function startOfDay(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

// Durable version history — the frontend already tracks a rich version log
// (Redux `state.versions`), but it only ever lived in Redux/localStorage, so it
// vanished on a fresh device/session and the "Restore" button's result silently
// reverted on next fetch. This mirrors each save into the (previously unused)
// WorkoutVersion collection so history survives reloads. Best-effort: a failure
// here must never block the actual workout save.
const VALID_REASONS = ['ai_adaptation', 'injury_detected', 'goal_change', 'user_override', 'recovery_low', 'equipment_change'];
async function snapshotWorkoutVersion(workout, userId, { changes, reason, aiExplanation, previousVersion }) {
  try {
    await WorkoutVersion.create({
      workoutId: workout._id,
      userId,
      version: workout.version,
      changes,
      reason: VALID_REASONS.includes(reason) ? reason : 'user_override',
      exercisesSnapshot: workout.exercises,
      workoutSnapshot: {
        title: workout.title,
        type: workout.type,
        splitFocus: workout.splitFocus,
        durationTarget: workout.durationTarget,
        exercises: workout.exercises,
        aiExplanation: workout.aiExplanation
      },
      previousVersion,
      aiExplanation: aiExplanation || ''
    });
  } catch (err) {
    console.error('[WorkoutVersion] snapshot failed (non-fatal):', err.message);
  }
}

function buildUserContext(user, overrides = {}) {
  return {
    name: user.name,
    age: user.profile?.age,
    gender: user.profile?.gender,
    fitnessLevel: user.profile?.fitnessLevel,
    goal: user.currentGoal,
    equipment: user.equipment || [],
    workoutDuration: user.preferences?.workoutDuration,
    injuries: (user.injuries || []).filter(i => i.isActive),
    chronicConditions: user.healthProfile?.chronicConditions || [],
    dislikedExerciseNames: user.preferences?.dislikedExerciseNames || [],
    ...overrides
  };
}

export async function generateWorkout(req, res) {
  try {
    const date = req.body?.date ? startOfDay(req.body.date) : startOfDay(new Date());
    const existing = await Workout.findOne({ userId: req.user._id, date });

    const cheatConfig = findCheatDayConfig(req.user, date, 'workout_only');
    if (cheatConfig) {
      const cheatFields = {
        title: 'Cheat Day', type: 'recovery', splitFocus: 'Rest', durationTarget: 0,
        exercises: [], isCheatDay: true, cheatMessage: getCheatMessage('workout_only'),
        aiExplanation: 'Configured cheat day — no workout generated by design.'
      };
      const workout = existing
        ? Object.assign(existing, cheatFields, { version: (existing.version || 1) + 1 })
        : new Workout({ ...cheatFields, userId: req.user._id, date });
      await workout.save();
      return res.json(workout);
    }

    const { focusGroups, title, splitFocus, ...contextOverrides } = req.body || {};
    const userContext = buildUserContext(req.user, contextOverrides);
    const aiWorkout = await generateWorkoutWithAI(userContext, { focusGroups, title, splitFocus });

    const previousVersion = existing?.version;
    const workout = existing
      ? Object.assign(existing, { ...aiWorkout, isCheatDay: false, cheatMessage: undefined, version: (existing.version || 1) + 1 })
      : new Workout({ ...aiWorkout, userId: req.user._id, date });
    await workout.save();

    await snapshotWorkoutVersion(workout, req.user._id, {
      changes: existing ? 'AI regenerated workout plan' : 'Initial baseline workout plan generated',
      reason: 'ai_adaptation',
      aiExplanation: workout.aiExplanation,
      previousVersion
    });

    res.json(workout);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function generateYogaWorkout(req, res) {
  try {
    const { date: dateInput, level, goal, focusArea, duration, ...rest } = req.body || {};
    const date = dateInput ? startOfDay(dateInput) : startOfDay(new Date());
    const existing = await Workout.findOne({ userId: req.user._id, date });

    const cheatConfig = findCheatDayConfig(req.user, date, 'workout_only');
    if (cheatConfig) {
      const cheatFields = {
        title: 'Cheat Day', type: 'recovery', splitFocus: 'Rest', durationTarget: 0,
        exercises: [], isCheatDay: true, cheatMessage: getCheatMessage('workout_only'),
        aiExplanation: 'Configured cheat day — no workout generated by design.'
      };
      const workout = existing
        ? Object.assign(existing, cheatFields, { version: (existing.version || 1) + 1 })
        : new Workout({ ...cheatFields, userId: req.user._id, date });
      await workout.save();
      return res.json(workout);
    }

    const activeInjuries = (req.user.injuries || []).filter(i => i.isActive);
    const yogaSession = buildYogaSession({ level, goal, focusArea, duration }, activeInjuries);

    const workout = existing
      ? Object.assign(existing, { ...yogaSession, isCheatDay: false, cheatMessage: undefined, version: (existing.version || 1) + 1 })
      : new Workout({ ...yogaSession, userId: req.user._id, date });
    await workout.save();

    res.json(workout);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getTodayWorkout(req, res) {
  try {
    const workout = await Workout.findOne({ userId: req.user._id, date: startOfDay(new Date()) }).sort({ createdAt: -1 });
    if (!workout) {
      return res.status(404).json({ exists: false, message: 'No workout generated yet for today.' });
    }
    res.json(workout);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getWorkoutRange(req, res) {
  try {
    const { from, to } = req.query;
    if (!from || !to) {
      return res.status(400).json({ message: 'Query params "from" and "to" (YYYY-MM-DD) are required.' });
    }
    const workouts = await Workout.find({
      userId: req.user._id,
      date: { $gte: startOfDay(from), $lte: new Date(new Date(to).setHours(23, 59, 59, 999)) }
    }).sort({ date: 1 });
    res.json(workouts);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

// Real persistence for client-side edits (swap, reshuffle, plan switch) — without
// this, those mutations only lived in Redux + localStorage and were silently
// discarded the next time fetchTodayWorkout ran, which read as "the button only
// works once."
export async function updateWorkoutEdit(req, res) {
  try {
    const { exercises, title, splitFocus, aiExplanation, type, durationTarget } = req.body || {};
    const workout = await Workout.findOne({ _id: req.params.id, userId: req.user._id });
    if (!workout) return res.status(404).json({ message: 'Workout not found' });

    // Real preference-learning signal: an exercise the user just swapped away from
    // gets recorded so future recommendations soft-penalize it — a small, honest
    // interpretation of "learn from interaction" rather than fabricated live retraining.
    if (exercises) {
      const swappedAwayNames = exercises.filter(ex => ex.isAISwapped && ex.originalExercise).map(ex => ex.originalExercise);
      if (swappedAwayNames.length > 0) {
        const existing = new Set(req.user.preferences?.dislikedExerciseNames || []);
        swappedAwayNames.forEach(name => existing.add(name));
        req.user.preferences.dislikedExerciseNames = Array.from(existing).slice(-30);
        await req.user.save();
      }
    }

    const previousVersion = workout.version || 1;
    const swappedNames = (exercises || [])
      .map((ex, i) => (ex.isAISwapped && workout.exercises?.[i] && workout.exercises[i].name !== ex.name ? `${workout.exercises[i].name} → ${ex.name}` : null))
      .filter(Boolean);

    if (exercises) workout.exercises = exercises;
    if (title) workout.title = title;
    if (splitFocus) workout.splitFocus = splitFocus;
    if (aiExplanation) workout.aiExplanation = aiExplanation;
    if (type) workout.type = type;
    if (durationTarget != null) workout.durationTarget = durationTarget;
    workout.version = previousVersion + 1;

    await workout.save();

    const { versionLabel, versionReason, versionExplanation } = req.body || {};
    await snapshotWorkoutVersion(workout, req.user._id, {
      changes: versionLabel || (swappedNames.length ? `Swapped ${swappedNames.join(', ')}` : exercises ? 'Workout exercises updated' : 'Workout details updated'),
      reason: versionReason || (swappedNames.length ? 'ai_adaptation' : 'user_override'),
      aiExplanation: versionExplanation || aiExplanation,
      previousVersion
    });

    res.json(workout);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getWorkoutVersions(req, res) {
  try {
    const workout = await Workout.findOne({ _id: req.params.id, userId: req.user._id });
    if (!workout) return res.status(404).json({ message: 'Workout not found' });
    const versions = await WorkoutVersion.find({ workoutId: workout._id, userId: req.user._id }).sort({ version: -1 });
    res.json(versions);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function updateWorkoutStatus(req, res) {
  try {
    const { status, totalReps } = req.body;
    const workout = await Workout.findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id },
      { status },
      { new: true }
    );
    if (!workout) return res.status(404).json({ message: 'Workout not found' });

    if (status === 'completed') {
      await applyStreakUpdate(req.user);
      recordWorkoutCompletion(req.user, { totalReps: totalReps || 0, durationMins: workout.durationTarget || 0 });
      await req.user.save();
    }

    res.json(workout);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function getStreak(req, res) {
  try {
    const state = getStreakState(req.user);
    res.json({ streak: req.user.streak || { current: 0, longest: 0 }, ...state });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function pauseStreak(req, res) {
  try {
    const user = await pauseStreakForToday(req.user);
    res.json({ streak: user.streak, ...getStreakState(user) });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}

export async function generateWeekOfWorkouts(req, res) {
  try {
    const weekStartDate = req.body?.weekStartDate ? startOfDay(req.body.weekStartDate) : startOfDay(new Date());
    const userContext = buildUserContext(req.user);
    const dayPlans = await generateWeeklyWorkoutPlanWithAI(userContext, weekStartDate.toISOString().split('T')[0]);

    const created = [];
    for (const dayPlan of dayPlans) {
      const date = new Date(weekStartDate);
      date.setDate(date.getDate() + dayPlan.dayOffset);

      const existing = await Workout.findOne({ userId: req.user._id, date });
      const { dayOffset, ...workoutFields } = dayPlan;
      const workout = existing
        ? Object.assign(existing, workoutFields)
        : new Workout({ ...workoutFields, userId: req.user._id, date });
      await workout.save();
      created.push(workout);
    }

    res.json(created);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
}
